apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: webdocker-ds
  namespace: default
spec:
  selector:
    matchLabels:
      name: webdocker-ds
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: webdocker-ds
    spec:
      hostNetwork: false
      hostPID: false
      containers:
      - image: docker.pkg.github.com/abuccts/webdocker/webdocker:latest
        name: webdocker
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        env:
        - name: SERVER_PORT
          value: 8080
        - name: DOCKER_SOCKET_PATH
          # absolute path for docker.sock, default path is /var/run/docker.sock
          value: /var/run/docker.sock
        - name: DOCKER_LIST_FILTERS
          # example filters for running containers with io.kubernetes.container.name=app label
          # reference: https://docs.docker.com/engine/api/v1.37/#operation/ContainerList
          value: '{"status":["running"],"label":["io.kubernetes.container.name=app"]}'
        ports:
        - name: webdocker-port
          containerPort: 8080
          hostPort: 8080
        volumeMounts:
          - name: docker-socket
            mountPath: /var/run/docker.sock
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
